export const GET_INTRO_MESSAGES="GET_INTRO_MESSAGES"
export const GET_OPTIONS_MESSAGES="GET_OPTIONS_MESSAGES"
export const GET_OPTIONS="GET_OPTIONS"
export const UPDATE_SUB_OPTION="UPDATE_SUB_OPTION"
export const CLEAR_STATE="CLEAR_STATE"
export const GET_API_DATA="GET_API_DATA"
export const UPDATE_SUB_OPTIONS="UPDATE_SUB_OPTIONS"
export const UPDATE_SOLUTION="UPDATE_SOLUTION"


export const SAVE_BUTTONS="SAVE_BUTTONS"


